config/routes.rb
Rails.application.routes.draw do

  root "memes#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :memes, only: [:index, :create, :show, :destroy, :update] do
        resources :reviews, only: [:index, :create, :new, :destroy, :update]
      end
    end
  end

  resources :memes, only: [:index, :new, :show] do
    resources :reviews, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :user
  has_many :reviews

  validates :title, presence: true
  validates :imageUrl, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :meme

  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    role == "admin"
  end

  has_many :memes
  has_many :reviews
end

app/controllers/api/v1/memes_controller.rb
class Api::V1::MemesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    memes = Meme.all
    render json: memes
  end

  def create
    user_input = JSON.parse(request.body.read)
    meme = Meme.new(
      user: user_signed_in,
      title: user_input["title"],
      imageUrl: user_input["imageUrl"],
      description: user_input["description"]
    )

    if meme.save
      render json: { meme: meme }
    else
      render json: { error: meme.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    meme = Meme.find(params[:id])
    user = user_signed_in
    render json: {meme: meme, current_user: user}
  end

  def destroy
    meme = Meme.find(params[:id])
    user = user_signed_in

    if user.id == meme.user.id || user.role == "admin"
      meme.delete
      render json: {id: params[:id]}
    else
      flash.now[:errors] = "You must be the creator of this meme to delete!"
      render json: {id: params[:id]}
    end
  end

  def update
    meme = Meme.find(params[:meme_id])
    if current_user.id == meme.user.id || current_user.role == "admin"
      meme.title = params[:title]
      meme.description = params[:description]
      if meme.save
        render json: {error: ""}
      else
        render json: {error: "Please enter a Title."}
      end
    else
      render json: {error: "You did not post these Meme."}
    end
  end

  private

  def user_signed_in
    current_user
  end

  def meme_params
    require(:meme).permit(:user_id, :title, :imageUrl, :description)
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    @meme = Meme.find(params[:meme_id])
    @reviews = @meme.reviews
    render json: @reviews
  end

  def create
    input_data = review_params
    input_data['user'] = current_user
    review = Review.new(input_data)
    if review.save
      render json: { review: review }
    else
      render json: { error: review.errors.full_messages },
        status: :unprocessable_entity
    end
  end

  def destroy
    review = Review.find(params[:id])
    if params[:review][:id].to_i == current_user.id || current_user.role == 'admin'
      Review.find(params[:id]).delete
      render json: {deletedReview: review}
    else
      render json: {id: params[:id]}
    end
  end

  def update
    review = Review.find(params[:id])
    review.rating = params[:rating]
    review.comment = params[:comment]
    if review.save
      render json: {error: ""}
    else
      render json: {error: "That is not a valid rating."}
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :meme_id, :rating, :comment)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @memes = Meme.all
    @user = current_user
  end

  def show
    @current_user = current_user
  end

  def new
    @meme = Meme.new
  end

  protected

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please sign in or create an account."
      redirect_to new_user_session_path
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def new
    @review = Review.new
    @user = current_user
  end

  protected

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please sign in or create an account."
      redirect_to new_user_registration_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MemeReviews</title>

  <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Open+Sans" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
    <a href="/"><h1>meme reviews</h1></a>
  </div>

  <div id="nav">
    <%- if current_user -%>
      <%= link_to 'Add A Meme', new_meme_path %>
      <span>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </span>
    <%- else -%>
      <%= link_to 'Sign Up', new_user_registration_path %>
      <%= link_to 'Sign In', new_user_session_path %>
    <%- end -%>
  </div>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/memes/index.html.erb
<div id='app'/>

app/views/memes/new.html.erb
<div class="new-meme">
  <div id='app'/>
</div>

app/views/memes/show.html.erb
<div id='app'/>